### ISSUE TITLE
Visualizer보드를 실행할 때마다 THREE.Loader 오류 발생, 최초 Rack 클릭시 Visualizer 초기화 됨.

### ISSUE THREAD

**Issue by heartyoh** [things-scene/visualizer#11]
![Screen Shot 2019-12-29 at 7 50 09 PM](https://user-images.githubusercontent.com/1239480/71555962-67d87280-2a75-11ea-811a-59f508565a77.png)

[ 영향 현상 ]
1. 비쥬얼라이저가 포함된 보드를 실행할 때마다 THREE.Loader 오류가 발생하나,
이 때까지는 보드상에 특별한 현상은 발견되지 않음.

2. 최초에 Rack을 클릭하면, 'Uncaught (in promise) TypeError: Cannot read property 'model_layer' of null' 오류가 발생하면서, 비쥬얼라이저가 초기 상태로 되돌아감.
그 이후부터는 정상동작함.

**Comment by lotstar87** [comment]
항목 2. scene.create 과정에서 baseUrl이 변경되어 모든 컴포넌트를 다시 그리는 것이 문제.

**Comment by ghost** [comment]
항목 1의 경우 ThreeJS가 업데이트되면서 삭제된 메소드를 호출하기 때문에 발생됐던 문제

`visualizer.js`
```javascript
THREE.DefaultLoadingManager.addHandler(/\.tga$/i, new TGALoader())
```
위 코드로 변경됨
