### ISSUE TITLE
things-factory에서 rack-table-cell의 location increase pattern이 작동하지 않음

### ISSUE THREAD

**Issue by dev-anais** [things-scene/visualizer#9]
rack-table-cell 우측 Property-Specific창내의 컴포넌트(things-editor-location-increase-pattern)에서 modeler에 접근하기 어려워, 기존의 컴포넌트를 그대로 사용하면 오류가 발생함 (클릭 이벤트를 처리하는 things-editor-location-increase-pattern에서 this는 modeller가 아니기 때문에)

**Comment by ghost** [comment]
`things-editor-location-increase-pattern.js`
```js
_handleRackTableCellIncrementSet(e) {
  let detail = e.detail

  var selected = this.selected[0].parent // ERROR: 'selected' is undefined

  var { increasingDirection, skipNumbering, startSection, startUnit } = detail

  this.scene.undoableChange(function() {
    selected.increaseLocation(increasingDirection, skipNumbering, startSection, startUnit)
  })
}
```

**Comment by ghost** [comment]
board-ui 모듈을 사용해 보드를 구현하는 경우에는 property editor에서 component에 접근할 수 없기 때문에 component에서 selected를 직접 editor에 넘겨주는 등의 방법을 사용해야 함
